### ISSUE TITLE
Not really a issue -- Suggestion

### ISSUE THREAD

**Issue by Hobolandjacob** [fkapitalism/HExBot#1]
removing the he2 banner at the top would be amazing lol plus it gets in the way if browser is small

**Comment by fkapitalism** [comment]
Yeah, that banner is really annoying. The problem doing that is the bot just starts to run after all DOM elements are loaded. I mean it's purposely a little bit slow. So, the bot can't remove the banner without it seems like kinda flasher. Hey, I've seen your work at your repo. Good job.
