### ISSUE TITLE
Nmap

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#10]
**_Nmap_**

Nmap's are now **_more useful_** than ever and **many** people use them on HE.
Now, for people who don't have Nmap's, don't worry, you'll get one soon enough.
It would be _nice_ to have a feature involving Nmap's. Here is what I'm thinking... upload a Nmap to an IP, Run it, Hide it, Delete Logs, Download Nmap Scan File, Delete File, Delete Logs, Delete Personal Logs.
This _probably_ isn't the most _effective_ way to go about doing it, but if you have a good enough **hider**, ( 3.0+ )
And a good enough hasher at this stage ( Recommended 3+ ) You should be okay to go.

This would be a great way to stash all of the IP's and bank logs and maybe even Bitcoin keys and accounts.

Also, if you manage to make all that work, try and make a subject inside of the settings saying "Do you want to record all IP's/Bank Info/Bitcoin Info into this box?" If the user clicks yes, then the operation goes as follows.

Upload Nmap
Run It
( Bot will look at all info and get all IP's/Bank Info/Bitcoin Info ((If there is a double of the same log, delete the duplicate until only 1 Log )) and save it into a data box within the bot )
Delete Nmap Scan File
Delete/Hide Nmap Itself.

This would be amazing if it was implemented.
Try your best,

- **_Mushy_**

( EDIT: Holy, I am finding a lot of opportunities and suggestions and bugs today, I'm on fire. )

**Comment by fkapitalism** [comment]
@MentalMushrooms I liked the Nmap idea. Maybe the concept could be appended to the webcrawler.

Actually the webcrawler is already programmed to grab all ips, bank info and bitcoin info.

**Comment by MentalMushrooms** [comment]
@fkapitalism Can you give me an EXTREMELY In-Depth tutorial into how the WebCrawler works?
I'm still a bit iffy about it.

**Comment by fkapitalism** [comment]
@MentalMushrooms Hahaha. Ok. Actually I'm going to create a wiki to share knowledges about HE and the Bot. I'll try to deploy that today.

**Comment by MentalMushrooms** [comment]
Thanks!

**Comment by fkapitalism** [comment]
I've just created a wiki. I'm not going to create that tutoral now. But you can write something there. ;)

**Comment by MentalMushrooms** [comment]
I dont have an account there yet, ill create it now
