### ISSUE TITLE
New Feature??

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#11]
**_New Feature??_**

New Feature - Scan for better software

This can be used as another section of the WebCrawler I guess...

It goes to one IP, See's if it has better software than the user currently has. If it does, download it delete logs and so forth.

So... 
Sequence Time

User Selects what software to upgrade and search for eg Cracker
His current cracker is 1.2
The user selects IP to search for better software. ( Best to probably start searching in the first puzzle location )
The bot does its job and goes to the IP
bot = omg, this IP has a 1.3 Cracker, let's delete logs first, then download it, and delete logs again!
And it basically continues forever e.e

Stay Mushy

- **_Mushy_**

**Comment by fkapitalism** [comment]
Nice. It would be a great feature for the webcrawler. BTW have you tested "Solve puzzle" button? It kinda do that. It goes through the puzzle servers and it auto improves the user cracker.

**Comment by MentalMushrooms** [comment]
I thought It just solved the puzzles. Delete the feature from the solve puzzle box, because its only meant for solving puzzles. e.e
