### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#12]
Teach me everything you know

**Comment by fkapitalism** [comment]
LOL

**Comment by fkapitalism** [comment]
Lets make a new module on hexbot

**Comment by fkapitalism** [comment]
This module will show a message always you open the mission tab. Are you ready? lol

**Comment by MentalMushrooms** [comment]
Im on ipad so if im slow and make typo's thats just me
And yus im redy

**Comment by MentalMushrooms** [comment]
Wait crap...

If im on a tablet/android device... I cant get hexbot...

**Comment by fkapitalism** [comment]
LOL

**Comment by MentalMushrooms** [comment]
What time are you online at usually?

Switch it to GMT 0 time so that I dont have to convert.

If this sort of works on a tablet, the coding bit, you can explain it to me with screenshots on whats actually happening with the bot right?

**Comment by MentalMushrooms** [comment]
If you dont have a screenshot making software, download lightshot and use it, i'll view the images to follow along @fkapitalism

**Comment by MentalMushrooms** [comment]
Assuming you are on a PC

**Comment by fkapitalism** [comment]
Well. Usually I'm online from 1am to 11pm. 
Hey my computer has the print screen button. hahaha

**Comment by fkapitalism** [comment]
If you are at Ipad you couldn't be able to code. :/

**Comment by MentalMushrooms** [comment]
I sort of can, inside github that is.

If ipad no work, we can do it tommorow 3PM+ GMT

**Comment by MentalMushrooms** [comment]
When im on my pc

**Comment by MentalMushrooms** [comment]
What is your time-zone?

**Comment by MentalMushrooms** [comment]
Nvm, a better question is, what time is it right now for you? ( 24 plz )

**Comment by fkapitalism** [comment]
Here is UTC-03:00

**Comment by fkapitalism** [comment]
It's about 8pm

**Comment by MentalMushrooms** [comment]
Check pull requests

**Comment by MentalMushrooms** [comment]
So you are 3 hours behind me in terms of time meaning that by the time I get on my pc at 15:00, you should already be online at 12:00 Noon or whatever it is.

**Comment by MentalMushrooms** [comment]
So we can work on the project for a max of 6 Hours

**Comment by MentalMushrooms** [comment]
@fkapitalism I can edit the code by sending a pull request but thats all I can do in the ipad. So your going to have to give me a bunch of insight into whats happening with the bot.

**Comment by fkapitalism** [comment]
LOL. What did you pull request me? Why don't you check out that problem on missions sequence where the bank is not closing? It's a good start.

**Comment by MentalMushrooms** [comment]
Because Idk how to code lol, I dont even know what half of it is in the first place

**Comment by MentalMushrooms** [comment]
Ill try my best to search for it. But even finding the code is going to be hard asf because idk where it is...

**Comment by fkapitalism** [comment]
LOL. You'll learn soon. What if we wait until you get you pc, tomorrow?

**Comment by MentalMushrooms** [comment]
Thats fine.
Just be sure to be on your pc at 12:00 for your time mkay?

**Comment by fkapitalism** [comment]
Ok. I'll be here. Cya

**Comment by MentalMushrooms** [comment]
I think i messed up the time calculation, lemme refigure this all out lol

**Comment by MentalMushrooms** [comment]
@fkapitalism What exact time is it for you right now?

**Comment by fkapitalism** [comment]
It's 8:12pm here right know

**Comment by MentalMushrooms** [comment]
Yeah yiu are 3 hrs behind me

**Comment by MentalMushrooms** [comment]
Make sure to be on your computer at 12 AM. I'll be online then and ready to be taught some coding lessons. And in the process,  I might edit a bit of the wiki.

I'll reopen this whenever im online.

For now, bye.

**Comment by MentalMushrooms** [comment]
In the meantime, take a look at the bank mission code but dont make changes to it. I want to see exactly whats wrong and how to fix it.

**Comment by fkapitalism** [comment]
Ok. I'll do it.

**Comment by MentalMushrooms** [comment]
Bye for now

**Comment by Hobolandjacob** [comment]
lol doesn't know how to code FEELSBADMAN go learn basic html then js

**Comment by MentalMushrooms** [comment]
I'll be on my pc in 7 hours from now.

**Comment by MentalMushrooms** [comment]
Bye for now

**Comment by MentalMushrooms** [comment]
@fkapitalism I'll be on my PC in 1 hr 30 mins from now

**Comment by fkapitalism** [comment]
@MentalMushrooms Yeah. Ok

**Comment by fkapitalism** [comment]
@MentalMushrooms Are you there?

**Comment by MentalMushrooms** [comment]
I'm here, its just I'm on my phone now, need to get Iron Supplements, I never eat meat that often e.e

**Comment by MentalMushrooms** [comment]
Will be on PC maybe 10 mins

**Comment by fkapitalism** [comment]
@MentalMushrooms I have to leave. I'm sorry. Can we talk tonight? Cya

**Comment by MentalMushrooms** [comment]
Sure but when tonight In your time?

**Comment by MentalMushrooms** [comment]
@fkapitalism

**Comment by MentalMushrooms** [comment]
Cant be online now, gtg to sleep.
Bye

**Comment by fkapitalism** [comment]
@MentalMushrooms  I've deployed a new version. I bet you'll love it. You can learn programming using this new feature. ;)

**Comment by MentalMushrooms** [comment]
Omg.

Wow.

How do I even begin?

This is amazing...

I need to learn all this damn coding lmao

Good Job

You have outdone yourself tremendously on the wiki and in the bot itself.

I'm going to become one of the "Scripters" On that "Credits" Tab in the bot, I'm telling you...

**Comment by MentalMushrooms** [comment]
Now I'm going to study all of that code till I figure out how to do it properly, then I'm going to learn coding to make a new module on the bot. ( Hopefully, and I have an idea for a new module. A tab on the bot to bring you back to the bot page, Basically the same as the settings but without having to close and reopen the bot to get back to the main menu screen. )

**Comment by MentalMushrooms** [comment]
@fkapitalism

**Comment by RobinKuiper** [comment]
This conversation tho xD

**Comment by MentalMushrooms** [comment]
Lol

**Comment by MentalMushrooms** [comment]
@fkapitalism You have to teach me in which order to put code in because I'm worried if i get the code in the wrong order e.e

**Comment by robin00hood** [comment]
Lawl

**Comment by fkapitalism** [comment]
@MentalMushrooms Don't worry about that. The code is kinda unbreakable. I mean, there is a sandbox to handle the code input. If something goes wrong it'll appear at debug field (the red one). Just keep trying to understand how the whole thing works. It's very easy actually.

**Comment by MentalMushrooms** [comment]
alright
