### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Optimusprimeagario** [fkapitalism/HExBot#14]
Hi, I know JavaScript (a bit), I started it year ago and I would like to work with you. You don't have to pay me. I just want some coding experience ;), and you could make a script with Node (server-side) which uses proxies and makes new accounts and sends the BTC to the user.

BTW I am 14.

**Comment by fkapitalism** [comment]
Absolutely. You may work with us. Fork and pull request if you improve something. The thing about Node this project isn't about it but why don't you try to do something?

**Comment by Optimusprimeagario** [comment]
Only thing that is separating for me to make a Node script is Google Recaptcha. I don't have that good skills to beat google's recaptcha xD

**Comment by fkapitalism** [comment]
Actually it's kinda impossible currently. Always someone breaks this recaptcha, google make things even harder.

**Comment by Optimusprimeagario** [comment]
I made a KeyCode and Cloudflare Error  script if you want to implement it in the script:  http://pastebin.com/raw/P99udayk

**Comment by Hobolandjacob** [comment]
lol there is no bypass for googles recaptcha which is why there are people being paid all day long to enter captchas for you.

**Comment by Optimusprimeagario** [comment]
did i say there is?
