### ISSUE TITLE
Fkapitalism Only

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#15]
https://discord.gg/mt7YS2p

Anyone else apart from fkapitalism will be banned from the server.

**Comment by MentalMushrooms** [comment]
Also, fkapitalism, if you do join the server, please read all text starting from the top-down and state discord name. If possible, show a screenshot showing me that it is you.

**Comment by fkapitalism** [comment]
Sure. Just me? 
No problem

**Comment by MentalMushrooms** [comment]
Join the server.

**Comment by MentalMushrooms** [comment]
And read.
