### ISSUE TITLE
WebCrawler

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#16]
**_WebCrawler_**

Now, it's been working fine till I noticed this.

My Custom Code ( For DDoS ) :

if(target.internet >= Mbits(24)){ //It checks if the target server has at least 24 Mbits of internet speed
  upload("*.vddos")
  seconds_limit(60)
} else
if(target.softwares("*").has("*.av") == false){ //It checks if the target server has an antivirus
  upload("*.vddos")
  seconds_limit(60)
}

And in the settings, i also have it set for the web-crawler to upload and install but only delete logs after installation, but whenever the ddos virus is installed and ran, **_it tries to hide it._**

**So... im probably going to switch back to the old web-crawler for now since this one is wasting my time quite a bit. And if you do get this fixed, can you also make a setting in the webcrawler to leave your IP Wide-Open in VPC? ( if i leave logs in NPC That'd mess me over ) Im the type of player that likes to leave logs wide open so i can get more IP's. And also because some people dont bother increasing their CPU Speed so it takes 1 Minute or more to clean logs. Even more time-wasting.**

**_Stay Mushy_**

**_- Mushy_**

**Comment by fkapitalism** [comment]
Hi Mushy. By default the webcrawler will install and upload.
If you just need to upload and nothing more use:
`
upload("software_name", "")
`
If you just need to install without hidding use:
`
upload("software_name", "install")
`

If you need to both install and hide, do not use the second parameter or use:
`
upload("software_name", "install & hide")
`

**Comment by fkapitalism** [comment]
Actually I'm going to change the default param. I think it's better the bot just upload without installing or hiding unless if explicitly defined.

**Comment by MentalMushrooms** [comment]
Okay. Will switch back to Custom Webcrawler tommorow. Thanks. Also check the discord server please.
