### ISSUE TITLE
Can't change bank to crawl

### ISSUE THREAD

**Issue by iiCarelessness** [fkapitalism/HExBot#17]
The only one listed is First International.

Doesn't let me type in another, either.
I also have Ultimate Bank, HEBC, etc, but they don't show up in the list.

**Comment by fkapitalism** [comment]
Have you created an account on these others banks?
It's working fine to me tho

**Comment by iiCarelessness** [comment]
Damn, that was it, thank you.

I can't believe I didn't think of that.
