### ISSUE TITLE
Suggestion: Research

### ISSUE THREAD

**Issue by iiCarelessness** [fkapitalism/HExBot#18]
Would you be able to add a feature to upgrade stuff?

Once it's upgraded, complete the task, clear logs?

That'd be awesome.

**Comment by MentalMushrooms** [comment]
Unfortunately, Captcha is a big bitch to Hexbot right now

And i've had this conversation before with the old hexbot mods, and they still cant make it happen.

So in other words, this is impossible right now.

**Comment by dominicusdev** [comment]
Yeah, I remember you @mentalmushrooms it's still a bitch, although, I may have found a solution.
