### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#2]
_**Issue/Suggestion**_

In the bot, I think the WebCrawler is kinda _broken_.
Why do I say this?
In the section "Starting by these Hosts" You put in the IP/IP's You want to hack with the programs and such right?
But instead, whenever I place in **ONE** IP Address, ( Or multiple addresses) it hacks the IP... Then goes on to hack **ALL** of the previous IP's you have **ALREADY** hacked. And I don't want to be putting in 20 addresses in the "Forget these IP's" Box.

Can you possibly find a better way to organise this or make another button with the same function, but only affecting **ONE IP**.

( Also, whenever you are using the bot and maybe you have finished doing a WebCrawl, the bot pops up again and it is annoying when **_we just don't need it_**. This happens for **almost every instruction** whenever it is completed. Any way to fix this by maybe inserting a hotkey to pop it up or do a specific instruction? )

( IMPORTANT! : Maybe this WebCrawler isn't broken, after all, maybe I was using it wrong. Maybe if you could give an in-depth tutorial on how to use it because it is a tad-bit confusing. Maybe take a look at the code, it might be a little faulty in some areas. )

- **_Mushy_**

**Comment by fkapitalism** [comment]
Hey Mushy. Thanks for the feedback. I know you are an old partner of this project.

1 - I have an idea to solve the problem of ignoring IPs that were previously checked. The WebCrawl will automatically insert the IP into the "Ignore these ips" field as soon as the bot logins the server.

2 - The bot pops up again after the instruction is done. This behavior was added for usability reasons. People that is using the bot for the first time need to have a clear idea how the whole think works. So the bot was designed to give a response as soon as possible. But I understand this behavior can be really annoying along the time. So I will add a checkbox to switch this behavior.

**Comment by MentalMushrooms** [comment]
Yes indeed, I was a frequent supporter for the bot whenever it was released.
These 2 solutions are viable.
Im still a little bit confused with the WebCrawler though.
I'll look into more detail with it asap and report back if there are some things iffy with it.

**Comment by fkapitalism** [comment]
@MentalMushrooms  Your suggestions were implemented. Check it out please.

**Comment by MentalMushrooms** [comment]
Will check it now.

**Comment by MentalMushrooms** [comment]
@fkapitalism Love the new popup instruction.

Still testing out the WebCrawler.
