### ISSUE TITLE
bot gets detected by cloudflare

### ISSUE THREAD

**Issue by ryan0307hk** [fkapitalism/HExBot#24]
when running webcrawler script, cloudflare seems to be able to recognise I was using the bot. The page comes out when I am trying to clear hacked server logs.

**Comment by MentalMushrooms** [comment]
Will test now and report back.

**Comment by MentalMushrooms** [comment]
Nope, just HE Servers fking you up. Sorry.

**Comment by MentalMushrooms** [comment]
Closed.

**Comment by fkapitalism** [comment]
@MentalMushrooms solved the issue.
