### ISSUE TITLE
Auto login (twitter, fb?)

### ISSUE THREAD

**Issue by mikkelbfriis** [fkapitalism/HExBot#29]
I recommend an automated login sequence for FB or Twitter, so that when these are used for an account it's an automated process, when the session gets killed after ~30-60 minutes

**Comment by dominicusdev** [comment]
@gresendesa wonder if you're still around, babe?

**Comment by AssHole12** [comment]
I can work on, it when you want to. So when ur not logged in anymore, it should log in?

**Comment by dominicusdev** [comment]
Yeah
