### ISSUE TITLE
Extension defaults to German

### ISSUE THREAD

**Issue by BaaBaaBruh** [fkapitalism/HExBot#31]
When i installed the extension, I see it in german. How do I fix this?

**Comment by BaaBaaBruh** [comment]
<img width="563" alt="screen shot 2017-04-08 at 11 04 58 pm" src="https://cloud.githubusercontent.com/assets/20072190/24835207/e2237caa-1caf-11e7-825d-e41b240bcf99.png">

**Comment by fkapitalism** [comment]
I'll fix it 
OMG

**Comment by BaaBaaBruh** [comment]
k ty

**Comment by fkapitalism** [comment]
fixed

**Comment by AssHole12** [comment]
lol im sorry :O
