### ISSUE TITLE
Download Centre

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#35]
Maybe not as important since Legacy is ending soon but...

Whenever you try to access and clean download centre, why not just use the download and download username and password?

e.e

**Comment by fkapitalism** [comment]
I don't worry about that. The program works fine without this trait. It would be more elegant, but it would take too much unnecessary effort.

**Comment by MentalMushrooms** [comment]
That's fine, good to see you are starting to be active again haha
