### ISSUE TITLE
Upgrade Cracker Problem

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#36]
While upgrading a cracker, the bot deletes the previous version, that shouldn't really be happening.

If a person hides your higher cracker, you still have another cracker which is only .1 in version thats lower.

This might not be viable for late game with high level crackers, but for stuff below 7.0, this should probably be toggled on, just in-case.

**Comment by fkapitalism** [comment]
Yes. I thought this behavior would upset someone sometime. I've made that way to avoid tricky configurations.
