### ISSUE TITLE
Medium Level Mission Security Bug

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#5]
_**Medium Level Mission Security Bug**_

**Security Improvement:** After transferring all money from the bank to your account, close the bank, making it **_100% Untraceable and Unhackable._**
This would be most effective to "Sort of" **Defend** yourself from Bank Transaction Watchers if they are slow.
**Consider implementing this.**

( EDIT: I haven't tried Bank Transfer Missions, so I don't yet know if this applies to that. )

Stay Mushy.

- **_Mushy_**

**Comment by fkapitalism** [comment]
I've watched the bot running and actually it closes the bank after the cleaning of logs. But it happens too quickly that it's hard to notice.

**Comment by MentalMushrooms** [comment]
Oh, that's alright then, it's just closing the account too fast for my eyes to register lol.
