### ISSUE TITLE
Possibilities?

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#6]
**_https://github.com/fkapitalism/hexperience_**

That has me interested, how well does it **combine** with this **Hexbot**?
I'm hoping to get a reply from @fkapitalism since he ( _I assume_ ) knows a bit about this Helper thing.
Is it useful in any way?
What features does it have that Hexbot doesn't?
Is it (In theory) safer than HexBot?

Please Reply

- _**Mushy**_

**Comment by fkapitalism** [comment]
That's is an tampermonkey script. I was looking at its functionalities just for curiosity. There are awesome functionalities there for managing IPs. It is pretty safe btw.

**Comment by MentalMushrooms** [comment]
@fkapitalism Can it be used in assistance with HexBot like...
Hexbot = Hey HExperience
HExperience = Hi Hexbot
Hexbot = Can I take a look at the IP Data you have collected for me?
HExperience = Sure thing man!
Hexbot = Omg, that's alot of IP's! I'm going to contact my user and see what he wants to do with it!
Hexbot Options = 1 : Upload Virus ( Virus name and software thing ) 2 : Check for better software
3 : Get a NMap Scan
User = I wanna upload a virus!!!
Hexbot = HExperience, gimme all dem IP's...
HExperience = Damm, you get all the love... ( Gives IP's )
Hexbot = ( Goes and does whatever user asks it to do )

**Comment by fkapitalism** [comment]
LOL. Dialogs between scripts are funny.
I was testing the hexbot and hexperience script together. But they kinda didn't get along one another. 
The whole thing gets messy when they decide to clean logs at the same time.

**Comment by MentalMushrooms** [comment]
Ahh okay.
