### ISSUE TITLE
Little Tweak Please

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#7]
**_Little Tweak _Please_**

This isn't _necessarily important_ to the bot, but it will make it a bit more _**Stylish...**_ ( In my opinion )
Let me explain.  **_( READ THE PICTURES FROM 1-4 )_**

![screenshot_1](https://cloud.githubusercontent.com/assets/17526514/23338839/c77324b4-fc0c-11e6-88ba-72cb6de76a94.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17526514/23338842/cd9b4ccc-fc0c-11e6-855c-ed7b13561771.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17526514/23338843/d12369b0-fc0c-11e6-85b3-79898fba5187.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17526514/23338844/d45366b2-fc0c-11e6-807c-88cb54211449.png)

If the pictures didn't kind of explain what I mean, the text will.
Whenever you log into HE, the bot is/or is not there.
Let's assume that it isn't popped up because I closed it or something along those lines...
So, whenever you click the (BOT) Icon at the top right, the bot pops up.
But, to close it, you can't just re-click the (BOT) Icon to close it, you HAVE To click the (X) Button in order to close it.
This isn't really the nicest approach to a stylish bot, as most games, I see if you click the same button that opened up a tab within the game, it would close it. ( Or be a nub and press the (X) Button )
It would be nice to make the (BOT) Icon do the same job as the (X) Button.

Stay Mushy!

- **_Mushy_**

( **_EDIT:_** @fkapitalism Can you move the (BOT) Icon beside the user's IP? I minimise my browser a bit to get the internet moving a bit quicker and you can't see the icon in the header. Also for stylish reasons. )
 
**_( EDIT: Just changed IP. )_**

**Comment by fkapitalism** [comment]
I got the idea. Thanks a lot for the feedback.
I going to code that today.

**Comment by MentalMushrooms** [comment]
@fkapitalism Thanks for the bot button fix
:3

**Comment by fkapitalism** [comment]
Ok. Suggestion deployed. Check it out, please.

**Comment by MentalMushrooms** [comment]
Works nicely, mind working in the wiki a bit more? Ill create a user and you can give me permissions to edit it.

**Comment by fkapitalism** [comment]
Everyone can edit it. Feel free to put things in order there. ;)
