### ISSUE TITLE
Software In Files.

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#8]
**_Software In Files._**

Software in Files is becoming a bit more used in HE To get stuff organized.
Recently, I have been using this organization method to help me organize. 
I ran WebCrawler on the First Puzzle IP Address to upload a software. Decent Spam.vspam:2.0
This Spam File was in a folder called "Other Stuff" ( not really necessary ) And it was un-hidden and able to use.
So I ran the Crawler, and it said that the software was not found/did not exist.
I moved the spam file out of the folder and it worked perfectly fine.

@fkapitalism Can you maybe add a feature to go into the folder and search for the software to upload or is this not possible due to folder stuff? 

Stay Mushy

**_- Mushy_**

**Comment by fkapitalism** [comment]
Yeah. This is a little bit tricky. But I'll try to implement. This isn't a promess, ok?

**Comment by MentalMushrooms** [comment]
@fkapitalism Sure.
Although this will be annoying...

**Comment by MentalMushrooms** [comment]
@fkapitalism You could maybe do it like this if you can

**_VERY BASIC CODING INCOMING_**

if any files on software = true,
check all files for specified file
if any files on software = false,
check on software page for specified file
if specified file not existing
otherwise, report "File not Found"

or

if any files on software = true,
check all files for specified file
if the file specified not in the folder,
search on the software page
if the file specified not in page,
otherwise, report "File not Found"

**Comment by fkapitalism** [comment]
LOL. I'll consider that! Thx

**Comment by MentalMushrooms** [comment]
Not a chance, idk how to code. I just learnt the if language from learning from somebody else doing it.
Do you mind teaching me how to code in jspaghetti? I'd be happy to help, I have quite a bit of free time.

**Comment by fkapitalism** [comment]
@MentalMushrooms No. I can teach you for sure. You could create a new module. What do you think?

**Comment by MentalMushrooms** [comment]
Just give me a butt load of info on everything like jspaghetti and modules, I joined github whenever hexbot was created and im still confused asf to what it can do, so far all I can do is reply and make issues/comment lol

**Comment by MentalMushrooms** [comment]
Also give me maybe a few yt vids on making edits to sites on 000webhost.com and yt vids on jspaghetti, it would help me out alot more.

**Comment by MentalMushrooms** [comment]
Youtube doesnt hold shit for jspaghetti,
I guess its manual teaching from now on lol

**Comment by fkapitalism** [comment]
That manual doesn't tell us everything the API can do, but it's a good start.

As soon as I know this API was created primarily to write the HExBot. It's not too popular.

000webhost is a web hosting where you can create servers. You just need create an account and get some app code to host there. For instance, the wiki I've just created, is a app called DokuWiki.

**Comment by MentalMushrooms** [comment]
Can you teach me in a new issue I will make called coding and it will be open? We dont need to talk here
