### ISSUE TITLE
Save Feature

### ISSUE THREAD

**Issue by MentalMushrooms** [fkapitalism/HExBot#9]
Make a save feature for the settings, like a file or something in the system that you can edit yourself maybe.

**Comment by MentalMushrooms** [comment]
P.S: I still havebnt been able to see the bot closing the bank, try looking over the code to make sure it is actually closing it.

**Comment by fkapitalism** [comment]
@MentalMushrooms I would like to use a storage or something to save the bot state. But this is unsafe once the data would be available to others scripts. I mean, it would make the bot trackable. :(

Ok. I'll double check the code to see the bank issue.

**Comment by MentalMushrooms** [comment]
Alright.
